name: Deploy Identifica treinamento

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: sudo apt-get update && sudo apt-get install -y sshpass rsync && sudo apt-get install -y expect
        
      - name: Acessando o Servidor
        run: expect sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}

        #      rsync -avz -e ssh ./ \
      - name: Fazendo o pull do repositorio
        run: cd ${{ secrets.REMOTE_TARGET }} && git pull origin main
          
