name: Deploy Identifica treinamento

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sync files to server
        run: |
          sshpass -p ${{ secrets.SSH_PASSWORD }} \
          rsync -avz -e ssh ./ \
          ${{ secrets.REMOTE_USER }}@ ${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_TARGET }}
