name: Deploy Identifica treinamento

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "SSH Pipeline finalizado"
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          connect_timeout: 10s
          script: |
            cd /var/www/html && 
            git pull &&
            echo $WELCOME