name: Deploy Identifica Treinamento LATAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Instalando as dependencias
      run: |
        # comando para instalar as dependências necessárias, caso haja
    - name: Deploy na Azure
      uses: easingthemes/ssh-deploy@v2.2.8
      with:
        SSH_PRIVATE_KEY: ''
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        # local-recursive: 'true'
        SOURCE: '/var/www/html'
        TARGET: '/var/www/html'