name: Deploy Identifica Treinamento LATAM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Instalando as dependencias
      run: |
        # comando para instalar as dependências necessárias, caso haja
    - name: Deploy na Azure
      uses: easingthemes/ssh-deploy@v2.2.8
      with:
        ssh-key: ''
        ssh-host: ${{ secrets.REMOTE_HOST }}
        ssh-port: ${{ secrets.REMOTE_PORT }}
        ssh-user: ${{ secrets.REMOTE_USER }}
        ssh-password: ${{ secrets.SSH_PASSWORD }}
        local-recursive: 'true'
        local-folder: '/var/www/html'
        remote-folder: '/var/www/html'